In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
# removing extra columns
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [7]:
## as all the features(values) are on the diff. scale, in order to bring them all in one scale -- we need to scale the values

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.59972646, -0.8473155 , -0.61276384, ..., -0.56188152,
         0.76521423, -0.25205225],
       [-0.22299624, -0.79881757, -0.22502422, ...,  0.8578358 ,
         1.00387297,  1.01509038],
       [-0.7346746 , -0.13139362, -0.75948712, ..., -0.75963215,
         0.64749741, -0.75528242],
       ...,
       [ 1.73094035, -1.14985023,  1.75065953, ...,  0.73311465,
        -0.87153326, -0.39146061],
       [-0.39730425, -0.38081156, -0.44897027, ..., -1.16595261,
        -1.19243252, -1.32821677],
       [-0.24267617, -1.05285436, -0.29615046, ..., -0.20454793,
        -1.41496568, -1.22564396]])

In [9]:
y_train

84     B
81     B
55     B
254    M
151    B
      ..
60     B
375    B
4      M
429    B
92     B
Name: diagnosis, Length: 455, dtype: object

In [10]:
## There are two classes in "y_train" and are represented in alphabet, we need to encode them so that NN can understand

# Label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,

## Numpy Arrays to PyTorch Tensors

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
X_train_tensor  # 1

tensor([[-0.5997, -0.8473, -0.6128,  ..., -0.5619,  0.7652, -0.2521],
        [-0.2230, -0.7988, -0.2250,  ...,  0.8578,  1.0039,  1.0151],
        [-0.7347, -0.1314, -0.7595,  ..., -0.7596,  0.6475, -0.7553],
        ...,
        [ 1.7309, -1.1499,  1.7507,  ...,  0.7331, -0.8715, -0.3915],
        [-0.3973, -0.3808, -0.4490,  ..., -1.1660, -1.1924, -1.3282],
        [-0.2427, -1.0529, -0.2962,  ..., -0.2045, -1.4150, -1.2256]],
       dtype=torch.float64)

In [16]:
y_train_tensor.shape

torch.Size([455])

## Defining the Model

In [17]:
class MySimpleNN():

    def __init__(self,X):
        self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad=True)   # dtype is chosen from "#1"
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad=True)

    def forward(self,X):   #2
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss


## Important Parameters

In [18]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

(create model -> Fordward Pass ->Loss calculate -> backward pass -> Update parameters (in single loop- till no. of epochs))

In [19]:
## create model

model = MySimpleNN(X_train_tensor)

## define loop
for epoch in range(epochs):
    ## Forward Pass (z = w.x + b and then apply sigmoid)
    y_pred = model.forward(X_train_tensor)   # from "#2"


    # Loss calculate
    loss = model.loss_function(y_pred, y_train_tensor) # This tells us how wrong the model’s predictions are


    # backward pass
    loss.backward()


    # Update parameters
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad     # new_weights = old_weights - learning_rate × gradient
        model.bias -= learning_rate * model.bias.grad

    # zero gradients (Clear old thoughts)
    # We need to clear the gradients before the next round
    model.weights.grad.zero_()
    model.bias.grad.zero_()


    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 4.000216013510977
Epoch: 2, Loss: 3.9141202973066624
Epoch: 3, Loss: 3.8228554702849937
Epoch: 4, Loss: 3.723897894341824
Epoch: 5, Loss: 3.618274683378596
Epoch: 6, Loss: 3.5081377906183246
Epoch: 7, Loss: 3.39184562573612
Epoch: 8, Loss: 3.270988880289906
Epoch: 9, Loss: 3.143580783547675
Epoch: 10, Loss: 3.0154528644065057
Epoch: 11, Loss: 2.8859283677977734
Epoch: 12, Loss: 2.7511908409689445
Epoch: 13, Loss: 2.6109599041288325
Epoch: 14, Loss: 2.467929146536876
Epoch: 15, Loss: 2.3171047585089517
Epoch: 16, Loss: 2.167413183288153
Epoch: 17, Loss: 2.020820225763993
Epoch: 18, Loss: 1.8763737574457031
Epoch: 19, Loss: 1.7314165902268923
Epoch: 20, Loss: 1.5933700542124232
Epoch: 21, Loss: 1.464669265626786
Epoch: 22, Loss: 1.3448733930262182
Epoch: 23, Loss: 1.237797761805481
Epoch: 24, Loss: 1.1439638972450397
Epoch: 25, Loss: 1.0635256694115927


In [20]:
# model.weights
# model.bias

In [21]:
model.weights


tensor([[-0.1588],
        [-0.2475],
        [-0.3381],
        [ 0.1942],
        [ 0.3140],
        [ 0.2543],
        [ 0.1793],
        [ 0.2301],
        [ 0.4149],
        [ 0.3731],
        [-0.3593],
        [ 0.7265],
        [ 0.0822],
        [ 0.4358],
        [ 0.0378],
        [ 0.0181],
        [ 0.1985],
        [ 0.1789],
        [-0.0315],
        [ 0.2522],
        [ 0.2246],
        [ 0.3446],
        [-0.0799],
        [-0.0247],
        [-0.1956],
        [ 0.3296],
        [-0.1604],
        [-0.2058],
        [-0.2813],
        [-0.0933]], dtype=torch.float64, requires_grad=True)

In [22]:
model.bias

tensor([-0.1105], dtype=torch.float64, requires_grad=True)

## Evaluation

In [23]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5761772990226746


Our main goal was not to increase the accuracy but to understand the training pipeline of NN in PyTorch