In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
# removing extra columns
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [ ]:
## as all the features(values) are on the diff. scale, in order to bring them all in one scale -- we need to scale the values

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.36434328,  0.4989619 , -0.38375934, ..., -0.885802  ,
        -0.68671322, -0.12422918],
       [-0.55121407, -1.35466224, -0.52945277, ..., -0.49015558,
         0.93834181,  0.48611162],
       [ 1.39677235,  1.28812861,  1.49055588, ...,  2.07144843,
         2.92783324,  1.12388975],
       ...,
       [ 1.37695272, -0.06538407,  1.2894579 , ...,  0.12075553,
        -0.10195845, -1.02574174],
       [ 0.22175147, -0.9784316 ,  0.18341903, ...,  0.01212871,
        -0.3554074 , -0.05591581],
       [-0.19162937, -0.10208949, -0.186355  , ...,  0.44051617,
         1.01951173,  0.1635829 ]])

In [ ]:
y_train

407    B
130    B
42     M
171    M
32     M
      ..
551    B
248    B
127    M
472    B
526    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
## There are two classes in "y_train" and are represented in alphabet, we need to encode them so that NN can understand

# Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,

## Numpy Arrays to PyTorch Tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
X_train_tensor  # 1

tensor([[-0.3643,  0.4990, -0.3838,  ..., -0.8858, -0.6867, -0.1242],
        [-0.5512, -1.3547, -0.5295,  ..., -0.4902,  0.9383,  0.4861],
        [ 1.3968,  1.2881,  1.4906,  ...,  2.0714,  2.9278,  1.1239],
        ...,
        [ 1.3770, -0.0654,  1.2895,  ...,  0.1208, -0.1020, -1.0257],
        [ 0.2218, -0.9784,  0.1834,  ...,  0.0121, -0.3554, -0.0559],
        [-0.1916, -0.1021, -0.1864,  ...,  0.4405,  1.0195,  0.1636]])

In [ ]:
y_train_tensor.shape

torch.Size([455])

## Defining the Model

In [ ]:
import torch.nn as nn

class MySimpleNN(nn.Module):

    def __init__(self,num_features):

        super().__init__()
        self.Linear = nn.Linear(num_features,1)
        self.Sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.Linear(features)  #z = wx +b
        out = self.Sigmoid(out)
        return out




## Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
#  define loss fxn:
loss_function = nn.BCELoss()

## Training Pipeline

In [ ]:
# create model

model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop

for epoch in range(epochs):

    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred,y_train_tensor.view(-1,1))

    # clear gradient
    optimizer.zero_grad()


    # backward loss
    loss.backward()

    # update parameters
    optimizer.step()


    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6157927513122559
Epoch: 2, Loss: 0.49380257725715637
Epoch: 3, Loss: 0.42277324199676514
Epoch: 4, Loss: 0.3755064010620117
Epoch: 5, Loss: 0.3412839472293854
Epoch: 6, Loss: 0.3151169419288635
Epoch: 7, Loss: 0.2943265438079834
Epoch: 8, Loss: 0.2773289680480957
Epoch: 9, Loss: 0.2631205916404724
Epoch: 10, Loss: 0.2510310709476471
Epoch: 11, Loss: 0.2405937761068344
Epoch: 12, Loss: 0.23147283494472504
Epoch: 13, Loss: 0.22341959178447723
Epoch: 14, Loss: 0.21624580025672913
Epoch: 15, Loss: 0.20980598032474518
Epoch: 16, Loss: 0.2039857804775238
Epoch: 17, Loss: 0.19869405031204224
Epoch: 18, Loss: 0.19385698437690735
Epoch: 19, Loss: 0.18941433727741241
Epoch: 20, Loss: 0.1853163093328476
Epoch: 21, Loss: 0.18152134120464325
Epoch: 22, Loss: 0.17799444496631622
Epoch: 23, Loss: 0.17470599710941315
Epoch: 24, Loss: 0.1716306507587433
Epoch: 25, Loss: 0.1687466949224472


(create model -> Fordward Pass ->Loss calculate -> backward pass -> Update parameters (in single loop- till no. of epochs))

In [ ]:
model.Linear.weight


Parameter containing:
tensor([[ 0.4156,  0.1951,  0.1119,  0.3059, -0.0772,  0.1965,  0.3112,  0.3718,
          0.0426, -0.0239,  0.1960, -0.0037,  0.2601,  0.0345,  0.0419, -0.1203,
         -0.1709,  0.0948,  0.0952, -0.0051,  0.1754,  0.1932,  0.2354,  0.1387,
          0.1274,  0.2721,  0.2319,  0.2240,  0.1146,  0.1299]],
       requires_grad=True)

In [ ]:
model.Linear.bias

Parameter containing:
tensor([-0.2390], requires_grad=True)

## Evaluation

In [ ]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5415512323379517


Our main goal was not to increase the accuracy but to understand the training pipeline of NN in PyTorch

In [ ]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()  # Using 0.5 as a threshold for binary classification
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5169283151626587
