In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("CUDA is available")
    print(f"Using Gpu : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


# Creating a Tensor

In [ ]:
# using empty

torch.empty(2,3)


tensor([[1.8261e+25, 4.3271e-41, 1.8261e+25],
        [4.3271e-41, 4.4842e-44, 0.0000e+00]])

In [ ]:
# type

type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand

torch.rand(2,3)       # it will create value between (0-1) and everytime we run the notebook, it will generate the random values

tensor([[0.7441, 0.2216, 0.0799],
        [0.9028, 0.2945, 0.1370]])

In [ ]:
# using seed

torch.manual_seed(100)   # it will generate the same random nos. whenever we run the notebook
torch.rand(2,3)



tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# generate custom tensors

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace     # linearly spaced
print("using linspace ->", torch.linspace(0,10,10))

# using eye         # identity matrix-- diagonal elms are "1" rest are "0"
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
type(x)

torch.Tensor

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) # will create the same dim. matrix like "x" but with diff. values

tensor([[493921239150, 489626271855, 390842023976],
        [210453397595, 214748364844, 219043332140]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)       # this will not work bcux rand-- generates the random nos. b/w (0,1)
# so we need to give the type
# torch.rand_like(x, dtype = torch.float32)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

# Tensor Data Type

In [ ]:
# find data type
x.dtype


torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# If I want to store them in float
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Tensors Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device("cuda")

In [ ]:
# creating a new tensor on GPU

torch.rand((2,3), device = device)

tensor([[0.8891, 0.4225, 0.8665],
        [0.6287, 0.7016, 0.7378]], device='cuda:0')

In [ ]:
# moving existing tensor to GPU

a = torch.rand(2,3)    # on cpu
print(a)

b = a.to(device)  # cpu --> gpu
print(b)

tensor([[0.7276, 0.2038, 0.6131],
        [0.6827, 0.1752, 0.9444]])


tensor([[0.7276, 0.2038, 0.6131],
        [0.6827, 0.1752, 0.9444]], device='cuda:0')

In [ ]:
## comparison b/w GPU and CPU

import torch
import time

## Define the size of the matrix
size = 10000   # large size for performance comparison

# create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)    # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time taken on CPU: {cpu_time:.4f} seconds")


# Move matrices to GPU

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to("cuda")

# Measure time on GPU

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)   # Matrix multiplication on GPU
torch.cuda.synchronize()    # ensure all the GPU Operations are complete
gpu_time = time.time() - start_time

print(f"Time taken on GPU: {gpu_time:.4f} seconds")


# Compare results

print('\nSpeedup (CPU time / GPU time):', cpu_time / gpu_time)

Time taken on CPU: 15.0462 seconds
Time taken on GPU: 0.7127 seconds

Speedup (CPU time / GPU time): 21.112673186770394
